### PR TITLE
Remove GitHub workflow and configuration files

### PR DESCRIPTION
**Pull request by eloonstra**
Deleted various GitHub actions workflows, funding configuration, and support files like `.gitignore` and `Makefile`. This cleanup suggests a switch in CI/CD strategy or a reorganization of project management tools.

### CODE REVIEW

**Comment by jamietanna** [comment]
@eloonstra what was the purpose of this? I don't believe I can see why this would be useful to our project

**Comment by eloonstra** [comment]
Was an accident on my side, my bad.

**Comment by jamietanna** [comment]
Ah, looks like this may be accidentally raised against our tree, looks like https://github.com/eloonstra/nullable/pull/3 is from your fork of the project

**Comment by eloonstra** [comment]
> Ah, looks like this may be accidentally raised against our tree, looks like https://github.com/eloonstra/nullable/pull/3 is from your fork of the project

Yeah, was creating multiple pull requests on my fork and accidentally clicked create too quickly 😅. You can delete this pull request through the virtual assistant on https://support.github.com/.

**Pull request closed without merging**
